export class Spp {
    id: number;
    // gmpj: string;
    // status_spp: string;

    // subdit_user: string;
    // subdit_keu: string;
    // subdit_scm: string;
    // status_selesai: string;
    // status_reject_to_user: string;
    // lain_lain: string;
    // total: number;

    nama_peng: any;
    deskripsi: any;
    prioritas: any;
    es_bud: any;
    target_spp: any;
    tw_spp: any;
    gmpj: any;
    gmdp: any;
    pic_pmo: any;
    pic_id: any;
    kode_io: any;
    anggaran: any;
    tahun_anggaran: any;
    tahun_po: any;
    pemilik_program: any;
    jpk: any;
    jp: any;
    no_spp: any;
    pic_spp: any;
    nilai_spp: any;
    tor: any;
    rab: any;
    kko: any;
    kkf: any;
    tanggal_spp: any;
    tgl_spp_ang: any;
    create_tgl_ang: any;
    tw_spp_real: any;
    tgl_spp_log: any;
    create_tgl_log: any;
    target_po: any;
    tw_po_plan: any;
    status_spp: any;
    note_spp: any;
    proker: any;
    sta_pro_ispp: any;
    tanggal: any;
    divisi: any;
    kendala: any;
    kriteria: any;
    jen_peng: any;
    milestone_spp: any;
    pic_log: any;
    no_po: any;
    pr: any;
    ket_po: any;
    tanggal_po: any;
    no_sp2k: any;
    tgl_sp2k: any;
    ttd_sp2k: any;
    tw_po_real: any;
    tang_ter_po: any;
    rekanan: any;
    dir_pek: any;
    region: any;
    mldp: any;
    ml_waspang: any;
    subdiv_pmo: any;
    pm: any;
    dirpek2: any;
    dirpek3: any;
    dirpek4: any;
    dirpek5: any;
    khs: any;
    jen_pek: any;
    nilai_rab: any;
    nilai_po: any;
    sta_perjanjian: any;
    perjanjian: any;
    no_perjanjian: any;
    ttd_perjanjian: any;
    tgl_perjanjian: any;
    baps1: any;
    baps2: any;
    baps3: any;
    baps4: any;
    baps5: any;
    basmp: any;
    jang_wak_mul: any;
    dead_set_amandem: any;
    dead_pek: any;
    sta_amandemen: any;
    amandemen: any;
    jen_amandemen: any;
    no_amandem: any;
    keterangan: any;
    sta_prog: any;
    evid_prog: any;
    tar_wak_sel_pro: any;
    per_plan_pro: any;
    per_prog_fis: any;
    tar_mas_pem: any;
    kel_dat_as_pro: any;
    ket_ser_ter: any;
    mi_ser_ter_op: any;
    tgl_ser_ter_op: any;
    no_baps1: any;
    tang_real_baps1: any;
    nom_real_baps1: any;
    tang_gr_baps1: any;
    nom_ter_gr_baps1: any;
    nom_ter_inv_baps1: any;
    status_baps1: any;
    no_baps2: any;
    tang_real_baps2: any;
    nom_real_baps2: any;
    tang_gr_baps2: any;
    nom_ter_gr_baps2: any;
    nom_ter_inv_baps2: any;
    status_baps2: any;
    no_baps3: any;
    tang_real_baps3: any;
    nom_real_baps3: any;
    tang_gr_baps3: any;
    nom_ter_gr_baps3: any;
    nom_ter_inv_baps3: any;
    status_baps3: any;
    no_baps4: any;
    tang_real_baps4: any;
    nom_real_baps4: any;
    tang_gr_baps4: any;
    nom_ter_gr_baps4: any;
    nom_ter_inv_baps4: any;
    status_baps4: any;
    no_baps5: any;
    tang_real_baps5: any;
    nom_real_baps5: any;
    tang_gr_baps5: any;
    nom_ter_gr_baps5: any;
    nom_ter_inv_baps5: any;
    status_baps5: any;
    no_basmp: any;
    tang_real_basmp: any;
    nom_real_basmp: any;
    tang_gr_basmp: any;
    nom_basmp_ter_gr: any;
    nom_basmp_ter_inv: any;
    status_basmp: any;
    nil_tot_ter_gr: any;
    nil_tot_real: any;
    tot_nil_real_ter: any;
    tot_nil_real_bel_bay: any;
    nil_dis_base_po_2015: any;
    pro_op_real: any;
    tipe_data: any;
    input_date: any;
    status: any;
    tgl_update_po: any;
    po_created_by: any;
    po_update_by: any;
    last_update: any;
    update_by: any;
    spp_created_by: any;
    spp_update_by: any;
    note: any;
    prestasi: any;
    new_update: any;
    date: any;
    flag: any;
    highlight: any;
    sta_up_pro_spp: any;
    target_app: any;
    pbs: any;
    last_send: any;
  updatedate: any;
//   updatedby: string;
  isdisplayed: any;
  createdate: any;
//   createdby: string;
}

// Class untuk tetap menampilkan Menu SideNav ketika halaman dibuka
export class Menu {
    authId?: string;
    menuParent?: string;
    menuId: string;
    read: any;
    write: any;
    text: string;
    items?: Menu[];
}
